#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for no.9 it displays "Hi"

i=0

while [ $i -lt 10 ]
do
  echo "Best School"
  ((i++))
  if [[ "$i" == '9' ]]; then
  echo "Hi"
  fi
done
