#!/usr/bin/env bash
# This script is displaying "Best School" 10 times but for no.4 it displays "Bad Luck"


i=0

while [ $i -lt 10 ]
do
  ((i++))
  if [[ "$i" == '4' ]]; then
  echo "bad luck"
  elif [[ "$i" == '8' ]]; then
  echo "good luck"
  else
  echo "Best School"
  fi
done
